"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const publications_1 = require("../data/publications");
const renderAuthors = (authors) => ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: authors.map((author, idx) => ((0, jsx_runtime_1.jsxs)("span", { children: [author.homepage ? ((0, jsx_runtime_1.jsx)("a", { href: author.homepage, target: "_blank", rel: "noopener noreferrer", className: "hover:underline", children: author.isBold || author.isUnderline ? ((0, jsx_runtime_1.jsx)("b", { children: author.isUnderline ? (0, jsx_runtime_1.jsx)("u", { children: author.name }) : author.name })) : (author.name) })) : (author.isBold || author.isUnderline ? ((0, jsx_runtime_1.jsx)("b", { children: author.isUnderline ? (0, jsx_runtime_1.jsx)("u", { children: author.name }) : author.name })) : (author.name)), author.isEqualContributor && '*', idx < authors.length - 1 && ', '] }, author.name))) }));
const PublicationList = ({ items }) => ((0, jsx_runtime_1.jsx)("div", { className: "space-y-10", children: items.map((item, i) => ((0, jsx_runtime_1.jsx)("div", { children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col md:flex-row md:justify-between md:items-start", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex-1", children: [item.award && (0, jsx_runtime_1.jsx)("div", { className: "mb-1", children: item.award }), (0, jsx_runtime_1.jsx)("div", { className: "text-xl font-bold", children: item.title }), (0, jsx_runtime_1.jsx)("div", { className: "text-gray-700 mb-1", children: renderAuthors(item.authors) }), item.equalContributionNote && ((0, jsx_runtime_1.jsx)("div", { className: "text-sm text-gray-500 mt-1", children: item.equalContributionNote })), item.links && ((0, jsx_runtime_1.jsx)("div", { className: "mt-2 flex flex-wrap gap-2", children: item.links.map((link, lidx) => ((0, jsx_runtime_1.jsx)("a", { href: link.url, target: "_blank", rel: "noopener noreferrer", className: "text-blue-600 hover:underline text-sm border border-blue-500 rounded px-2 py-1", children: link.label }, lidx))) }))] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-2 md:mt-0 md:text-right min-w-[120px]", children: [(0, jsx_runtime_1.jsxs)("div", { className: "font-bold text-gray-800", children: [item.venue, " ", item.year] }), (0, jsx_runtime_1.jsx)("div", { className: "text-gray-500", children: item.status })] })] }) }, i))) }));
exports.default = PublicationList;
//# sourceMappingURL=PublicationList.js.map